#EXCLUDED FILE TYPES
extend-exclude = [".git", "__pycache__", "data", "tools", "env", "venv"]


# GROUP VIOLATIONS BY FILE
output-format = "full"


[lint]
ignore = ["E203", "E501"]

extend-select = ["I"]